title: taras kalapun
subtitle: 
author: Taras Kalapun
simple_search: http://google.com/search
tagline:          
description:      ""

# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://kalapun.com

safe:        true
future:      true
lsi:         false
pygments:    true
markdown:    redcarpet

date_format: "ordinal"

subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false

paginate: 10
paginate_path: "blog/page/:num"
recent_posts: 5

excerpt_separator: "<!-- more -->"
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

logo:             
disqus_shortname: xslim-github

# Facebook Like
facebook_like: false

# Gravatar plugin
gravatar_hash: 4374a44a5a6642a24ac2975b9aa2dfe7
     
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:    "http://plus.google.com/+TarasKalapun"

# feed: http://feeds.feedburner.com/RestlessPoint

google_analytics: UA-2087894-2
google_verify: 
bing_verify:   
alexa_verify:


maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: [smart]

## redcarpet
## fenced_code_blocks

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false
  

include: [".htaccess"]
exclude: ["vendor",".bundle","lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "codekit-config.json", "Gemfile", "Gemfile.lock", "README.md", "node_modules", "Gruntfile.js", "package.json"]

 # Prose settings
prose:
  rooturl: '_posts'
  siteurl: "http://kalapun.com"
  relativeLinks: 'http://kalapun.com/api/prose/links.jsonp'
  media: 'images'
  ignore:
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - &pm_layout
        name: "layout"
        field:
          element: "hidden"
          value: "post"
      - &pm_title
        name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Title of a post"
      - &pm_published
        name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: true
      - &pm_comments
        name: "comments"
        field:
          label: "Allow comments"
          element: "checkbox"
          value: true
      - &pm_tags
        name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options: "http://restlesspoint.com/api/prose/tags.jsonp"
          alterable: true
      - &pm_description
        name: "description"
        field:
          element: "textarea"
          label: "Description"
          placeholder: "An article description that will be shown on homepage"
          value: ""
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          alterable: true

