# Site settings
title: taras kalapun
email: t@kalapun.com
author: Taras Kalapun
description: An it-problem solver and adrenaline junky. Sailing, skydiving, scuba diving, motorcycling and off-road racing are just someways I get away from the programming screen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kalapun.com" # the base hostname & protocol for your site

google_analytics: UA-2087894-2

permalink: /posts/:title/
relative_permalinks: false

markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink"]

highlighter: pygments

gems:
  - jekyll-redirect-from #https://help.github.com/articles/redirects-on-github-pages

collections:
  projects:
    output: true
    permalink: /projects/:path/
    layout: project

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      category: "posts"
  -
    scope:
      path: "projects"
      type: "projects"
    values:
      layout: "project"

social:
  email: mailto:t@kalapun.com
  phone: tel:+31621695865
  github: http://github.com/xslim
  linkedin: http://linkedin.com/in/tkalapun
  facebook: http://facebook.com/tkalapun
  flickr: http://flickr.com/xslim
  rss: http://feeds.feedburner.com/kalapun


prose:
  siteurl: "http://emilyvernon.com"
  ignore:
    - /_layouts
    - /_includes
    - /_sass
    - /css
    - /fonts
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: true
